name: Daily Auto Commits

on:
  schedule:
    - cron: "30 18 * * *"   # 12:00 AM IST
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kolkata

    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name "deepakavadhani"
          git config user.email "deepakavadhani@users.noreply.github.com"

      - name: Daily commit
        run: |
          echo "daily update - $(date)" >> updates.txt
          git add updates.txt
          git commit -m "[chores] daily auto commit"
          git push origin master

          
      - name: Daily commit
        run: |
          echo "daily update - $(date)" >> updates.txt
          git add updates.txt
          git commit -m "[chores] updated updates.txt"
          git push origin master

      - name: Daily commit
        run: |
          echo "daily update - $(date)" >> updates.txt
          git add updates.txt
          git commit -m "[chores] updated updates.txt"
          git push origin master

      - name: Daily commit
        run: |
          echo "daily update - $(date)" >> updates.txt
          git add updates.txt
          git commit -m "[chores] updated updates.txt"
          git push origin master

      - name: Daily commit
        run: |
          echo "daily update - $(date)" >> updates.txt
          git add updates.txt
          git commit -m "[chores] updated updates.txt"
          git push origin master

      - name: Daily commit
        run: |
          echo "daily update - $(date)" >> updates.txt
          git add updates.txt
          git commit -m "[chores] updated updates.txt"
          git push origin master

      - name: Daily commit
        run: |
          echo "daily update - $(date)" >> updates.txt
          git add updates.txt
          git commit -m "[chores] updated updates.txt"
          git push origin master

      - name: Daily commit
        run: |
          echo "daily update - $(date)" >> updates.txt
          git add updates.txt
          git commit -m "[chores] updated updates.txt"
          git push origin master
